[versions]
jdaVersion = "5.1.0"
jwizardLibVersion = "latest"
kotlinVersion = "2.0.20"
lavalinkProtocolVersion = "4.0.8"
logbackVersion = "1.5.7"
okHttpVersion = "4.12.0"
reactorVersion = "3.7.0"
reactorKotlinVersion = "1.2.3"
shadowJarVersion = "8.1.1"
slf4jApiVersion = "2.0.16"

[libraries]
jda = { module = "net.dv8tion:JDA", version.ref = "jdaVersion" }
jwizardLib = { module = "pl.jwizard:jwizard-lib", version.ref = "jwizardLibVersion" }
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlinVersion" }
kotlinReflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinVersion" }
lavalinkProtocol = { module = "dev.arbjerg.lavalink:protocol", version.ref = "lavalinkProtocolVersion" }
logbackCore = { module = "ch.qos.logback:logback-core", version.ref = "logbackVersion" }
logbackClassic = { module = "ch.qos.logback:logback-classic", version.ref = "logbackVersion" }
okHttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okHttpVersion" }
reactor = { module = "io.projectreactor:reactor-core", version.ref = "reactorVersion" }
reactorKotlin = { module = "io.projectreactor.kotlin:reactor-kotlin-extensions", version.ref = "reactorKotlinVersion" }
slf4jApi = { module = "org.slf4j:slf4j-api", version.ref = "slf4jApiVersion" }

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinVersion" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinVersion" }
kotlinSpring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlinVersion" }
shadowJar = { id = "com.github.johnrengelman.shadow", version.ref = "shadowJarVersion" }
