name: Release new version

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  generate-docs:
    runs-on: self-hosted
    env:
      ROOT_PATH: "/var/www/jwizard-docs/jwc/${{ github.ref_name }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate KDoc documentation
        run: ./gradlew dokkaHtml --no-daemon

      - name: Copy HTML documentation into http server
        run: |
          mkdir -p $ROOT_PATH
          rm -rf $ROOT_PATH/*
          cp -r docs/* $ROOT_PATH

  release:
    runs-on: ubuntu-latest
    needs: generate-docs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push repository tags
        run: git push --tags

      - name: Determinate tags range
        run: |
          tags_range=$(current=${{ github.ref_name }} \
            && prev=$(git describe --tags --abbrev=0 "$current"^ 2>/dev/null) \
            && [ -n "$prev" ] && echo "$prev..$current" || echo "$current")
          echo "tags_range=$tags_range" >> $GITHUB_ENV

      - name: Generate Changelog
        run: |
          echo "[KDoc for this release](https://docs.jwizard.pl/jwc/${{ github.ref_name }})" >> changelog.md
          echo "" >> changelog.md
          echo "### Changes" >> changelog.md
          git log --oneline --no-merges --pretty=format:"* %h - %s" $tags_range >> changelog.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body_path: changelog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
